- name: Deploy VM from template
  hosts: "{{ vm_name | default('rheltest') }}"
  become: yes

  tasks:
    - name: Check connectivity
      ping:
    
    - name: Configure MOTD
      template:
        src: templates/motd.j2
        dest: /etc/motd
        mode: 0644
